
mylist =[1,2,3]

print(mylist) # [1,2,3]

mylist2=["one",2,True,5.6]

print(mylist2) # ["bir",2,True,5.6]

list1=["one","two","three"]

list2=["four","five","six"]

list1+=list2 # list1 = list1 + list2

print(list1) # ['one', 'two', 'three', 'four', 'five', 'six']

print(len(list1)) # print(len(['one', 'two', 'three', 'four', 'five', 'six'])) => print(6) => 6

print(list1[3]) # three

userA = ["John",36]

userB = ["Johny",2]

print(userA) # ["John",36]

print(userB) # ["Johny",2]

users=[userA,userB] # users=[['John', 36], ['Johny', 2]]

print(users) # [['John', 36], ['Johny', 2]]

print(users[1]) # ['Johny', 2]

print(users[1][1]) # 2

